### ISSUE TITLE
Any way to improve performance

### ISSUE THREAD

**Issue by guranu** [ggerganov/whisper.cpp#1232]
Hi, i was wondering on how to improve performance in whisper.cpp? in llama.cpp you can improve performance by changing batch size number but since there isn't such an option i was wondering if there's other ways of improving performance time.

**Comment by pudepiedj** [comment]
I don't claim any technical competence, so this is just a report of my experience in case it helps.
I've been using whisper in various forms, starting from paying for it on the OpenAI API, then using Colab, then I discovered whisper.cpp, and since then I haven't used anything else.
The single biggest step-up in transcription speed has come from CoreML (if you ignore buying a new laptop!) I find the **base.en** and **tiny.en** models amazingly accurate on recorded speech, and I can now transcribe a 900 second audio *.wav file converted from *.mp4 by **ffmpeg** in about 10 seconds on an M2 Max with 32GB RAM and **base.en**, with minimal errors, which is twice as fast as CPU only on the same machine, although even that compares very well with all the other methods. The OpenAI API paid version used to take at least 30s, often more, and Colab more again.
What kinds of improvement in performance are you looking for? Is it just time or also accuracy etc.?

**Comment by Nullarity** [comment]
> What kinds of improvement in performance are you looking for? Is it just time or also accuracy etc.?

Not sure what @guranu is looking for, but I'm trying to use whisper.cpp to build my own voice assistant. Unfortunately, I can't get close to the appropriate performance/accuracy even for the wake phrase. On my machine (i9-13900, 64Gb RAM, no GPU), the tiny.en has about a 20% accuracy (which isn't acceptable), and the large model is about 95%, but a 3-second recording takes ~3 minutes to transcribe. I tried using pricey professional microphones with noise cancelling for voice recognition but didn't see any significant improvements.

So, I'm quite confused. I can't even come close to, let's say, the small, low-powered Google Home device, which recognizes "Hey Google" very quickly and accurately. I'm not a true data engineer, so I probably am missing something.

**Comment by bobqianic** [comment]
> So, I'm quite confused. I can't even come close to, let's say, the small, low-powered Google Home device, which recognizes "Hey Google" very quickly and accurately. I'm not a true data engineer, so I probably am missing something.

You might want to feed some prompts to the model. The challenge is that your audio clip is quite short, making it hard for the model to predict the right words. Keep in mind that Whisper's maximum context window is only 224 tokens. Anything beyond that gets cut off.

**Comment by pudepiedj** [comment]
> Hi, i was wondering on how to improve performance in whisper.cpp? in llama.cpp you can improve performance by changing batch size number but since there isn't such an option i was wondering if there's other ways of improving performance time.

I have not used whisper.cpp for translation because I am a native English-speaker, but my experience with transcription has been very positive: high levels of accuracy even with the **tiny.en** model, and under the latest GPU-enabled updates so fast that it would be churlish to complain (a 15-minute audio file transcribes very accurately in about 10 seconds using **ggml-base.en.bin**). What kind of performance improvements are you looking for?

**Comment by isaac-mcfadyen** [comment]
> which recognizes "Hey Google" very quickly and accurately

In general, wake word detection is very different from general transcription and all of the big voice assistants use different models for each.

Wake word models are trained on many examples of the specific phrase for waking ("OK Google", "Siri", "Alexa", etc) and are trained to ignore everything else, whereas Whisper is trained to recognize anything. I wouldn't expect Whisper to perform well on wake word tasks; in general, I'd run a wake word specific model all the time and then only run Whisper on the command/spoken text.

If you're looking for efficient wake word engines, you can try https://picovoice.ai/platform/porcupine/ (commercial but free for personal use) and https://github.com/dscripka/openWakeWord (works particularly well and is very low powered).

There's also an interesting video from the Amazon Alexa team about this subject: https://www.youtube.com/watch?v=kYrw2cC9dvs

**Comment by Nullarity** [comment]
@isaac-mcfadyen Thank you very much for your reply!

> In general, wake word detection is very different from general transcription and all of the big voice assistants use different models for each.

Now, I see that. Some very basic ideas can take time to grasp without familiarity with machine learning. I started using Porcupine and it works quite well.
