### ISSUE TITLE
Any way to disable non-voice transcriptions?

### ISSUE THREAD

**Issue by infinityp913** [ggerganov/whisper.cpp#1324]
Is there any way to disabled non-voice transcriptions like “(laughing)” and “* DING *”, “(Wind Whooshing)” and (Typing sounds).  
Whisper.cpp transcribes these sounds however my application requires just human speech.

**Comment by MathiasSchindler** [comment]
This might be an issue with the source whisper model provided by openai. I have seen other non-voice artifacts such as copyright notes or remarks from a parliament plenary debate such as "[Applause from the left]"

**Comment by infinityp913** [comment]
Yeah, that's what I thought too. I figured OpenAI had  a way to disable it and by extension this Whisper.cpp too. Surprised that aren't a lot of issues about this. I'd guess for most use cases you wouldn't want those non-voice transcriptions

**Comment by bobqianic** [comment]
> Is there any way to disabled non-voice transcriptions like “(laughing)” and “* DING *”, “(Wind Whooshing)” and (Typing sounds).

Unfortunately, the option you're looking for doesn't exist. This is due to the way words like `(laughing)` are handled, as they can be broken down into smaller pieces by the tokenizer, making it tricky to penalize or filter out specific tokens without unintended consequences. Transformer models like Whisper have a specific context length (`224` tokens in this case) which includes tokens from your initial prompt as well as past transcription results. Even minor tweaks can significantly alter the resulting output. You could potentially address this by writing some code to filter out specific phrases from the transcription results. Another approach worth exploring is using a prompt to tackle this issue.

<img width="331" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/129547291/75203271-c72d-4d27-b721-1a29e4727819">

**Comment by infinityp913** [comment]
I understand. I figured there might have been a Whisper transformer model not trained on those words. Filtering the output of the model is the way to go. Thanks!

**Comment by Pratik-Ghute** [comment]
"--suppress-nst"  -does this if you ran whisper-cpp with whisper server for other methods also the parameter will  be there
