### ISSUE TITLE
Converting whisper model to openvino fails

### ISSUE THREAD

**Issue by sp00ktober** [ggerganov/whisper.cpp#1354]
Morning, im trying to follow the steps from the Readme to convert the whisper model to openvino (to try it on my rPI4). Im doing this in a docker container on my Windows PC, installed the `openvino-conversion-requirements.txt`

Running `python convert-whisper-to-openvino.py --model large` with the `large` model produces the following error after a while:

```
100%|█████████████████████████████████████| 2.87G/2.87G [19:57<00:00, 2.58MiB/s]
/models/whisper.cpp/models/openvino_conv_env/lib/python3.10/site-packages/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
Killed
```

Is the large model not supported? Am i doing something wrong?
This also happens on the `medium` model.

**Comment by sp00ktober** [comment]
Maybe as addition, running the same commands on my rPI4 4GB (with insane 12GB swap, booted from a USB3 ssd, ubuntu server 2023) results in `Segmentation fault (core dumped)`.
Not sure why, i thought maybe because of OOM thats why i increased the swap file but im not sure if increasing it further would solve this.

**Comment by bobqianic** [comment]
> convert the whisper model to openvino (to try it on my rPI4).

Wait, does the Raspberry Pi 4 support OpenVINO? Isn't it exclusive to the Intel x86 platform?

**Comment by sp00ktober** [comment]
![grafik](https://github.com/ggerganov/whisper.cpp/assets/79335616/d2f25cd2-444e-49ff-bbb3-46704f30f9f3)
At least Pi 4 Model B is listed [here](https://github.com/openvinotoolkit/openvino) and i succeeded in compiling OpenVINO from sources on it, altho it took more or less a day to complete.

**Comment by bobqianic** [comment]
```console
/models/whisper.cpp/models/openvino_conv_env/lib/python3.10/site-packages/whisper/model.py:166: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
```

First of all, the `"error"` you see is actually a `"warning"`. This won't halt the conversion process. The real issue arises from the poorly defined output path for the converted model. Using relative paths is generally not advisable.

https://github.com/ggerganov/whisper.cpp/blob/62b81276e02f48070c3fd1e265e319f3604bfb39/models/convert-whisper-to-openvino.py#L32

With a few tweaks, it's possible to successfully convert Whisper models to OpenVINO models.

<img width="530" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/129547291/45c6a7c0-62c6-436e-ad08-c4dc16d37131">

I'm not certain why the process terminates on your side. I speculate it might be due to excessive RAM consumption, surpassing the resource limits you've set for the docker container.

<img width="580" alt="image" src="https://github.com/ggerganov/whisper.cpp/assets/129547291/cc0b3fdc-236d-420e-a2a6-1a32d94e0bdc">
