### ISSUE TITLE
Complied main.exe that can probably be used on Windows 10/11 x64 PCs

### ISSUE THREAD

**Issue by regstuff** [ggerganov/whisper.cpp#146]
One of my teammates compiled an exe and it was working quite well on most of our other Windows systems, so I thought I'd share it for those having difficulties compiling in Windows. 

It is available [here](https://github.com/regstuff/whisper.cpp_windows/releases/tag/v0.0.1). Unzip into a folder and use main.exe the same way you would use ./main.

You may need to install vcredist_x64. Get it [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

I've tested the exe on 5 WIndows 10/11 systems, and it worked on 4 of them. The fifth, where it didn't work was an old system with a lot of issues. Possibly that was the reason for failure.

FYI, in case this does not work for you, not sure if I can help anyone debug because I have minimal technical knowledge about building in Windows. 

@ggerganov let me know if you want to incorporate the exe into this repo, or whatever else you think appropriate. I just dumped it into a separate repo for lack of any better ideas.

**Comment by ggerganov** [comment]
Hi @regstuff ,
The Windows build is currently a weak point of the project, mainly because I don't have this operating system available to test with.

Having a precompiled executable is good for a quick way to see the capabilities of the model, but since it is not something that I have built myself, I cannot add it to the repo.

I think having a detailed guide or build instructions for Windows would be more beneficial.
Something like a step-by-step tutorial for the compiler installation and the various runtime libraries that are necessary to build the project.

**Comment by RYucel** [comment]
Looking for" a step-by-step tutorial for the compiler installation and the various runtime libraries that are necessary to build the project." on a windows machine

**Comment by ggerganov** [comment]
@RYucel 

See the Windows steps here:

https://github.com/ggerganov/whisper.cpp/actions/runs/3517978497/workflow#L117-L144

Or check cross-compilation instructions here:

https://github.com/ggerganov/whisper.cpp/issues/168
