### ISSUE TITLE
Offloading the whole model to GPU VRAM instead RAM

### ISSUE THREAD

**Issue by LSXPrime** [ggerganov/whisper.cpp#1628]
I am Whisper.cpp C# binding Whisper.Net with cuBLAS backend and noticed that when i load models (distil-whisper-large-v2-fp32 in my case) it take 3GB from my RAM but nothing from GPU VRAM, even thought the VRAM always empty while my RAM already on 90% usage.
using RTX 3060 12GB
RAM Crucial 16GB DDR4

can models be loaded directly to GPU VRAM ?

**Comment by JJones780** [comment]
I'm not using C# bindings but that shouldn't be the issue?
It may help get attention if you confirmed that you compiled using WHISPER_CUBLAS=1 .
 
`WHISPER_CUBLAS=1  make -j `

Otherwise please report what the GPU memory usage is when you use whispercpp directly or via one of the example programs ( which will need to be compiled with the WHISPER_CUBLAS flag as well ).

**Comment by LSXPrime** [comment]
I tried to build using CUBLAS with commit @447d49530c9af41fe24f2ae510f452903dba330d but it was the same, now I lost my GPU a month ago so I can't test this right now, but maybe it fixed in later commits.

**Comment by jensdraht1999** [comment]
@LSXPrime Can we close this issue?

**Comment by LSXPrime** [comment]
sorry, I opened it a long time ago that I forgot about it.
