### ISSUE TITLE
Sample SwiftUI app crashes on model load

### ISSUE THREAD

**Issue by cyrilzakka** [ggerganov/whisper.cpp#1748]
The accompanying SwiftUI example app crashes on all models tested on the assert:
```
whisper_init_from_file_with_params_no_state: loading model from '/private/var/containers/Bundle/Application/FBE0AA37-658E-4E0E-A5D7-326D14E1C818/whisper.swiftui.app/models/ggml-tiny.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 1 (tiny)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: picking default device: Apple A16 GPU
ggml_metal_init: loading '/var/containers/Bundle/Application/FBE0AA37-658E-4E0E-A5D7-326D14E1C818/whisper.swiftui.app/ggml_ggml.bundle/default.metallib'
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =    73.61 MiB, (   74.73)
whisper_model_load:    Metal buffer size =    77.18 MB
whisper_model_load: model size    =   77.11 MB
whisper_backend_init: using Metal backend
ggml_metal_init: allocating
ggml_metal_init: picking default device: Apple A16 GPU
ggml_metal_init: loading '/var/containers/Bundle/Application/FBE0AA37-658E-4E0E-A5D7-326D14E1C818/whisper.swiftui.app/ggml_ggml.bundle/default.metallib'
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     7.88 MiB, (   82.61)
whisper_init_state: kv self size  =    8.26 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     8.80 MiB, (   91.41)
whisper_init_state: kv cross size =    9.22 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     0.02 MiB, (   91.42)
whisper_init_state: compute buffer (conv)   =   12.17 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     0.02 MiB, (   91.44)
whisper_init_state: compute buffer (encode) =   64.92 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     0.02 MiB, (   91.45)
whisper_init_state: compute buffer (cross)  =    4.01 MB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =     0.02 MiB, (   91.47)
GGML_ASSERT: /Users/cyril/Library/Developer/Xcode/DerivedData/whisper.swiftui-hhqhmpnunsnndifjnxdzearbqgyp/SourcePackages/checkouts/ggml/src/ggml.c:4772: b->type == GGML_TYPE_I32
```
and more specifically: `GGML_ASSERT(b->type == GGML_TYPE_I32);`. 

Models tested from here: https://huggingface.co/ggerganov/whisper.cpp/tree/main and included small, tiny, medium and large. Tested on iPhone 14 Pro and iOS 17

**Comment by zapsleep** [comment]
I can confirm. Observing the same issue in my app with iPhone 14 Pro, iOS 17.
Crash on `GGML_ASSERT(b->type == GGML_TYPE_I32);` when trying to load a model.
The only thing I've changed from the last time it worked was updating whisper.cpp to 1.5.4.

I also think that maybe whisper.cpp Package.swift should point to a specific ggml commit instead of `master`. Trying to set the exact version 1.5.4 for whisper.cpp in XCode result in error message:
`Failed to resolve dependencies Dependencies could not be resolved because package 'whisper.cpp' is required using a stable-version but 'whisper.cpp' depends on an unstable-version package 'ggml' and root depends on 'whisper.cpp' 1.5.4.`

**Comment by ggerganov** [comment]
Yes, the upstream `ggml` has been recently updated and it is now incompatible. The problem is that Package.swift pull the latest `master` in `ggml`.

We should change it to a specific commit. Anyone want to give this a try and open a PR?
Need to use this commit: https://github.com/ggerganov/ggml/commit/8bf3f009e653f6bdac893c4bb6441f88ee55fe48

**Comment by nank1ro** [comment]
> Yes, the upstream `ggml` has been recently updated and it is now incompatible. The problem is that Package.swift pull the latest `master` in `ggml`.
> 
> We should change it to a specific commit. Anyone want to give this a try and open a PR? Need to use this commit: [ggerganov/ggml@8bf3f00](https://github.com/ggerganov/ggml/commit/8bf3f009e653f6bdac893c4bb6441f88ee55fe48)

You may check https://github.com/ggerganov/whisper.cpp/pull/1750
