### ISSUE TITLE
where is cuBLAS ?

### ISSUE THREAD

**Issue by Jds1234** [ggerganov/whisper.cpp#2665]
where is CPP cuBLAS ?
 it has gone from CPP 1.7.3.
CPP cuBLAS no longer listed as an option in subtitle edit program.

**Comment by niksedk** [comment]
The `windows-cublas` is no longer built as part of the CI action.
I think it changed in this commit: https://github.com/ggerganov/whisper.cpp/commit/668930a989863c5a4da718b7357446539fbf438a

Was this on purpose?

**Comment by ggerganov** [comment]
I disabled it because I wasn't able to fix it: https://github.com/ggerganov/whisper.cpp/commit/472464453defc8b7644f110177f8e4738b4464e3

I don't have a Windows environment, so it takes me a lot of time to debug this through Github Actions. If someone can figure out why it is failing - please submit a PR to resolve it.
