### ISSUE TITLE
make stream fails due to missing dependency

### ISSUE THREAD

**Issue by DaniruKun** [ggerganov/whisper.cpp#50]
If you normally try to build `stream` with `make stream`, it will fail with:
```
g++ -O3 -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wno-unused-function -pthread stream.cpp ggml.o whisper.o -o stream `sdl2-config --cflags --libs`
/bin/sh: 1: sdl2-config: not found
stream.cpp:12:10: fatal error: SDL.h: No such file or directory
   12 | #include <SDL.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:76: stream] Error 1
```
The missing dependency for this is https://www.libsdl.org/ and can be installed with:

```bash
sudo apt-get install libsdl2-dev
```

Would be nice to add this to the README, I might do this later if I have time.

**Comment by sstoner** [comment]
To install SDL2 on a M1, use the command `brew install sdl2`.

**Comment by tcnevin** [comment]
> To install SDL2 on a M1, use the command `brew install sdl2`.

This was a struggle for me too compared to Windows. 
I had to git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch --unshallow
but since that directory didn't exist yet I had to 
mkdir /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask
and then 
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask" fetch
without --unshallow
and also
git -C "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core" fetch --unshallow
then 
brew update
brew doctor
and finally
brew install sdl2
and then I could
make stream

works great now.
