### ISSUE TITLE
transcription time 2.7x than wav file

### ISSUE THREAD

**Issue by i-am-neo** [ggerganov/whisper.cpp#69]
Thanks for sharing whisper.cpp @ggerganov.  Wondering if I'm missing something.  I tried whisper.cpp on a 40-minute wav file, which took almost 2 hours to transcribe, which doesn't seem to be what others have experienced.  I tried transcribing on an 8-vcpu machine, 32 gb of memory.  Any settings I'm missing?  Appreciate your help.

Unfortunately I'm unable to share the wav file as it's private data.  

`
whisper_model_load: loading model from 'models/ggml-large.bin'
whisper_model_load: n_vocab       = 51865
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 1280
whisper_model_load: n_audio_head  = 20
whisper_model_load: n_audio_layer = 32
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 1280
whisper_model_load: n_text_head   = 20
whisper_model_load: n_text_layer  = 32
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 5
whisper_model_load: mem_required  = 4576.00 MB
whisper_model_load: adding 1608 extra tokens
whisper_model_load: ggml ctx size = 3255.34 MB
whisper_model_load: memory size =   304.38 MB
whisper_model_load: model size  =  2950.66 MB

main: processing 'output/x.wav' (38688821 samples, 2418.1 sec), 4 threads, lang = en, task = transcribe, timestamps = 1 ...
whisper_print_timings:     load time =  4246.85 ms
whisper_print_timings:      mel time = 31377.23 ms
whisper_print_timings:   sample time =  3421.71 ms
whisper_print_timings:   encode time = 4697475.00 ms / 146796.09 ms per layer
whisper_print_timings:   decode time = 1830579.38 ms / 57205.61 ms per layer
whisper_print_timings:    total time = 6568016.00 ms
`

**Comment by Topping1** [comment]
at least from my experience, I have seen good performance using the tiny, base and small models. Medium model is at least for me 1.1x. I guess the large model is too much even for these optimizations. One thing to take into account is that the transcription quality between medium and large should not be that different (see original paper for reference)

**Comment by ArtyomZemlyak** [comment]
You can check my test performance on new Xeon:
https://github.com/ggerganov/whisper.cpp/issues/16

And its not fast for large model

**Comment by ggerganov** [comment]
@i-am-neo 
I see that your machine has 8 cores. You can try to pass `-t 8` to `main` in order to use all 8 CPU cores. This might improve the performance to some extend. In my experience, going beyond 8 threads does not help with the performance, so no need to try this.

But yeah, the large model is quite heavy for CPU.

@ArtyomZemlyak 
By the way, the performance of the original python implementation was significantly improved yesterday after fixing the KV caching.

**Comment by i-am-neo** [comment]
@ggerganov Thanks. I had tried -t 8 before the run above.  -t 8 had clocked in ~4.16x.  Not sure why. Stats below.  

For what it's worth, I did also try the python implementation post-KV cache fix on the same audio - its execution time was ~4.62x.

Stats (-t 8):
```
whisper_model_load: loading model from 'models/ggml-large.bin'
...

whisper_print_timings:     load time = 32345.44 ms
whisper_print_timings:      mel time = 23386.80 ms
whisper_print_timings:   sample time =  4511.08 ms
whisper_print_timings:   encode time = 3918137.00 ms / 122441.78 ms per layer
whisper_print_timings:   decode time = 6024227.00 ms / 188257.09 ms per layer
whisper_print_timings:    total time = 10003485.00 ms
```

Execution time notwithstanding, with `-t 8`, the transcript got stuck in a loop around 31 minutes in, all the way to the end.  This behavior did _not_ manifest itself without -t 8.
```
[31:28.072 --> 31:29.072]   I'm going to skip it.
[31:29.072 --> 31:30.072]   Okay.
[31:30.072 --> 31:35.080]   I'm going to skip it.
[31:35.080 --> 31:36.080]   Okay.
[31:36.080 --> 31:37.080]   I'm going to skip it.
[31:37.080 --> 31:38.080]   Okay.
[31:38.080 --> 31:39.080]   I'm going to skip it.
[31:39.080 --> 31:40.080]   Okay. 
[31:40.080 --> 31:41.080]   I'm going to skip it.
[31:41.080 --> 31:42.080]   Okay.
[31:42.080 --> 31:43.080]   I'm going to skip it.
[31:43.080 --> 31:44.080]   Okay.
```

**Comment by ggerganov** [comment]
The repetition is very likely a result of using the Greedy sampling strategy - it's not ideal and can sometimes fail in the observed way. This will be improved in the future. There is an `--offset` parameter that can be used to restart the transcription before the point of failure:

https://github.com/ggerganov/whisper.cpp/issues/68#issuecomment-1283446297

The `-t 8` producing different result compared to `-t 4` is expected. Due to the different order in which the floating point operations are performed when using different number of threads, the round-off errors will be different and will eventually accumulate and  manifest in different results in the end. It's possible to make the computation reproducible regardless of the number of threads, but it will require some extra work and refactoring to achieve this. Not a high priority at the moment.

It's strange that using `-t 8` has worse performance compared to `-t 4` on an 8-core machine. My experience so far using the computers that I have access to is that the performance improves up to 8 threads given that the machine has at least 8 cores.
I guess, in your case it is best to run the computation on a short audio using different `-t` values and see which one is the best. It will likely by `-t 4`, but just in case.

**Comment by openconcerto** [comment]
Using perf tools, it seems that the program spend a major part of cpu time in ggml_compute_forward_mul_mat_f16_f32
by converting f16 <->f32. (vcvtph2ps mainly)
The second point is IMHO to investigate page faults from __memset_avx2_unaligned_erms .

Wouldn't be better to convert everything to f32 at startup? Or use f16 if it doesn't imply to many computation errors?

**Comment by ggerganov** [comment]
@openconcerto 

There is already support to run the entire model in F32 mode. In order to use it you need to generate a model file that contains F32 weights, like this:

```
python3 models/convert-pt-to-ggml.py ~/.cache/whisper/small.pt /path/to/openai/whisper models/ 1
```
The `1` at the end enables F32 conversion of the weights.

You then run `main` as usual, specifying the newly generated F32 model file.
I just tried doing that with the `small` model and I observed the following results:

- on `M1 Pro`, the F16 mode is 2 times faster compared to F32 mode
- on `AMD Ryzen 9 3900X` the F16 mode is ~10-15% faster compared to F32 mode

The `M1 Pro` result is expected since there are intrinsics to operate directly with F16 data (e.g. `vfmaq_f16`). The loss of precision is not big trouble during inference.

On `x86` we don't have F16 intrinsics so we have to convert to F32. From the observed result, I believe that when we use the F32 model the computation is memory bound and when we use the F16 model - it is CPU bound. But I very well might be wrong.

Regarding the page faults - not sure. I read that nowadays unaligned access has pretty much the same performance as aligned, so I didn't put effort to guarantee aligned memory.

**Comment by openconcerto** [comment]
Thanks to your comments, I was able to convert the small and base models to their F32 version.

Using the small or base model, I got a memory assertion : 
ggml_new_tensor_impl: not enough space in the context's memory pool.

I tried to increase the pools size in the map defined in whisper.cpp... but it didn't helped a lot.

Using valgrind on "main" with the working F16 models, "segment overflow in thread" is reported.

**Comment by ggerganov** [comment]
A quick hack to fix this is to change the following line:

https://github.com/ggerganov/whisper.cpp/blob/f3dae90c31a9f4828446c70785f8981f04e1f291/whisper.cpp#L132

to

```c++
static const size_t MB = 3*1024*1024; 
```

**Comment by openconcerto** [comment]
Thanks, I was able to make some benchmarks and tweaks.

I was able to speedup a bit the F32 version, but my manual tweaks are outperformed by gcc ... using -march=native -mtune=native
As you mentioned, cache misses are the main issue. I guess that to switch to a full F16 code is the way to go (and is that what you plan if I read correctly your TODOs ;) )

I looked how other libs are acheiving best performance on matrix multiplications. All is done in assembly by carefully tweaking the prefetecher and using AVX. 
Maybe using OpenBLAS is an option, but I miss knownledge on your code to dig on its feasability.

**Comment by ggerganov** [comment]
Yes, OpenBLAS is an option.
On Mac OS / iOS I already use BLAS since it comes out-of-the-box by simply adding `-framework Accelerate` to the compile flags. On other platforms, it's slightly more complicated process since you have to install a third-party library.

Adding it would most likely offer some performance improvement.
I think, following the `GGML_USE_ACCELERATE` macros in `ggml.c` as an example can be a good starting point for adding OpenBLAS support, since the `Accelerate` API has the same BLAS interface. The change shouldn't be very big actually. Might give it a try at some point.

**Comment by openconcerto** [comment]
Using what you did for MacOS, in 10 minutes I had a working OpenBLAS version.
The gain is **huge**, from 50s to 22s.

For developer who want to try :

1/ apt install libopenblas-dev

2/ add /usr/lib/x86_64-linux-gnu/libopenblas.a in the link command

3/ add #include <cblas.h> in ggml.c
  and uncomment the code in ggml_compute_forward_mul_mat_f32  related to GGML_USE_ACCELERATE

(I removed _if (ggml_compute_forward_mul_mat_use_blas(src0, src1, dst))_ )

**Comment by ggerganov** [comment]
Ha!! This is huge! Very interesting

**Comment by i-am-neo** [comment]
@openconcerto 
Was your speedup via OpenBlas on the medium or large model?

**Comment by openconcerto** [comment]
Reenabling _if (ggml_compute_forward_mul_mat_use_blas(src0, src1, dst))_  improved the performance.
I use the base (fp32) model with t=1 (t=2 improve by 30% the performance, but t>2 has no gain with OpenBLAS)

From perf tool, the hotspots changed.

Before
```
  55,50%  main     main                  [.] ggml_compute_forward_mul_mat_f32
  26,97%  main     main                  [.] ggml_compute_forward_flash_attn_f16
   5,89%  main     main                  [.] ggml_graph_compute_thread
   1,18%  main     libc.so.6             [.] __memset_avx2_unaligned_erms
   1,18%  main     main                  [.] ggml_compute_forward_gelu_f32
   1,06%  main     main                  [.] ggml_compute_forward_conv_1d_2s_f32
   0,80%  main     main                  [.] ggml_compute_forward_dup_f32
   0,44%  main     main                  [.] ggml_compute_forward_add_f32
```

After

```
  19,90%  main     main                  [.] ggml_graph_compute_thread
  16,66%  main     main                  [.] ggml_compute_forward_flash_attn_f16
  10,00%  main     [kernel.kallsyms]     [k] syscall_return_via_sysret
   7,47%  main     [kernel.kallsyms]     [k] syscall_exit_to_user_mode
   6,12%  main     main                  [.] sgemm_kernel_HASWELL
   5,74%  main     [kernel.kallsyms]     [k] entry_SYSCALL_64_after_hwframe
   4,13%  main     [kernel.kallsyms]     [k] __entry_text_start
   3,48%  main     main                  [.] ggml_graph_compute
   1,59%  main     [kernel.kallsyms]     [k] __schedule
   1,21%  main     main                  [.] ggml_compute_forward_mul_mat_f32
```

**Comment by Topping1** [comment]
> /usr/lib/x86_64-linux-gnu/

@openconcerto can you please show what changes did you make to the makefile? I have not much experience with compiling programs. Thanks

**Comment by ArtyomZemlyak** [comment]
For me worked next:

1. In this line https://github.com/ggerganov/whisper.cpp/blob/master/Makefile#L24 :
`LDFLAGS = -lcblas`

2. Also i commented this lines: https://github.com/ggerganov/whisper.cpp/blob/master/ggml.c#L77-L79

But i not shure in this solution

**Comment by openconcerto** [comment]
> > /usr/lib/x86_64-linux-gnu/
> 
> @openconcerto can you please show what changes did you make to the makefile? I have not much experience with compiling programs. Thanks

To statically link, just use:
$(CXX) $(CXXFLAGS) main.cpp whisper.o ggml.o /usr/lib/x86_64-linux-gnu/libopenblas.a -o main $(LDFLAGS)

**Comment by erkkimon** [comment]
I noticed that on the same computer (OSX) using any model, Firefox is about 5 X faster than Chrome. Another interesting note is that even Chrome on my Android phone (OnePlus Nord 2) is faster than desktop Chrome on any of my computers.

**Comment by ggerganov** [comment]
OpenBLAS is now supported via the `WHISPER_SUPPORT_OPENBLAS` CMake option

**Comment by i-am-neo** [comment]
@ggerganov Thank you very much. Great work!

**Comment by xyx361100238** [comment]
> A quick hack to fix the memory issue is to change the following line:
> 
> https://github.com/ggerganov/whisper.cpp/blob/f3dae90c31a9f4828446c70785f8981f04e1f291/whisper.cpp#L132
> 
> to
> 
> ```c++
> static const size_t MB = 3*1024*1024; 
> ```


I have  change the memory，but got error：

> GGML_ASSERT: ggml.c:5824: false
Aborted (core dumped)
![image](https://user-images.githubusercontent.com/19569322/199704582-7201fac7-bba4-4510-b4fb-4bcd5c488eb1.png)

**Comment by ggerganov** [comment]
Looks like you have enabled "Flash Forward":

https://github.com/ggerganov/whisper.cpp/blob/d5afebd37c8267ce83cd2ec6a5994f2f20941859/whisper.cpp#L19

This is not implemented in FP32 mode yet

**Comment by xyx361100238** [comment]
it works！
