### ISSUE TITLE
ESP32 (Arduino) support

### ISSUE THREAD

**Issue by maxbrito500** [ggerganov/whisper.cpp#717]
Hello,

Thank you for the fantastic work. Since it is written in plain C/C++ without dependencies, perhaps it would be possible to ask for whisper to run on ESP32 devices?

This would a great combination for enabling the embedded devices with such capable voice recognition skills.

Thank you.

**Comment by ggerganov** [comment]
Maybe the upcoming 4-bit tiny models could fit on some embedded devices.
Closing until the 4-bit work is completed - then we can discuss again

**Comment by Stonelinks** [comment]
Any thoughts on revisiting this? I know its probably impossible but would love edge inference of voice to be possible on small embedded platforms like ESP / arduino.

For context, I was thinking of hacking SMS support to https://skysedge.com/unsmartphones/RUSP/ so you could just speak into the phone (which is just an arduino mega) and it transcribes to a text message to be sent.

**Comment by barshag** [comment]
@ggerganov  4-bit seems  to be  ready.
Any recipe how to implement it on Arduino board based?

**Comment by HarrySoteriou** [comment]
@stonelinks With 4 bit quantization the tiny.en model is around 24MB but still RAM requirements are in the order of 177MB if I am not mistaken. How do you plan on bringing that down to less than 16MB (11 fold reduction) ? External RAM? Offload parameters from RAM to Flash at the expense of speed ?

**Comment by Stonelinks** [comment]
Yeah I think after reflecting, it would be impossible. Or maybe possible but way to slow for anything approaching realtime voice transcription (like in my example).

I thought maybe some kind of virtual memory thing could page chunks of the model weights in and out of RAM from flash? All the intermediate states would need to be stored when this happens. Sounds hard to implement unless something like `mmap` can do the heavy lifting and map outside of RAM on to flash for embedded targets, which I seriously doubt.

Anyway, since I seriously want that arduino rotary phone thing to be able to text at some point, likely the cell modem on there could send voice samples to a small server running whisper, and return the result to the phone.

**Comment by Stonelinks** [comment]
Edit: I think after research, the forward pass of the inference is the step that would need to be carefully modified in order to load chunks of the model in from the SD card such that actual memory consumption on the target device is minimized. I don't even know what the most minimal chunk to split the weights on for processing. Layer? Neuron?

Like I said, I've no idea how feasible this is. Sounds difficult and painfully slow even if it managed to work.

**Comment by mmackh** [comment]
The esp32 p4 came out with much better performance- maybe this will make it more feasible?
