### ISSUE TITLE
CoreML low ANE usage, high CPU usage?

### ISSUE THREAD

**Issue by mirozahorak** [ggerganov/whisper.cpp#801]
All works great with CoreML, but i was wondering why is most of the time CPU 100% and ANE goes to 30% max, and only maybe 1/5 of the time.
See graphs from asitop. only occasionaly is ANE going up to 30 %, when CPU goes down.
Is this normal behaviour on M1 Air?
<img width="1102" alt="Screenshot 2023-04-19 at 16 02 22" src="https://user-images.githubusercontent.com/29453355/233100169-80ce34be-f7c1-493c-9af1-bf6d927fbd70.png">
<img width="1099" alt="Screenshot 2023-04-19 at 16 02 10" src="https://user-images.githubusercontent.com/29453355/233100191-38171067-9baf-4b63-b5ab-f8092a423244.png">

**Comment by neurostar** [comment]
I believe that it is normal.
If you are wondering why it is not utilize ANE continuously, you can read discussion on the development of the ANE implementation. It is mainly decoder part is still running on CPU due to limitation of ANE. 
https://github.com/ggerganov/whisper.cpp/discussions/548

I'm seeing similar asitop graph on M2 air as well.
