### ISSUE TITLE
Error using q8_0 quantize model, works OK on q5_1 model.

### ISSUE THREAD

**Issue by kafan1986** [ggerganov/whisper.cpp#846]
I have tested on Tiny en model and it works on q5_1 model but throws error on below line. I am initializing model using python APIs.

```
self.ctx = whisper_cpp.whisper_init_from_file(model.encode('utf-8'))
OSError: [WinError -529697949] Windows Error 0xe06d7363
```

Also, there is regression in terms of memory usage. Earlier memory usage was optimized down to 129 MB for tiny model. Now it is showing around 209MB.

Using latest commit from master branch.

**Comment by ggerganov** [comment]
Should work now with latest `master`

**Comment by kafan1986** [comment]
@ggerganov Tested. It works but performance wise it clearly a regression. All the quantized as well as the full model now takes, more memory as well the inference timings has significantly deteriorated.

**Comment by ggerganov** [comment]
What CPU are you using?

I am optimizing mainly for Apple Silicon and the performance has never been better on M1 Pro:

| CPU | OS | Config | Model | Th | Load [ms] | Encode [ms] | Commit |
| --- | -- | ------ | ----- | ------- | --------- | ----------- | ------ |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | tiny | 7 | 43 | 95 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | tiny-q5_0 | 7 | 31 | 108 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | tiny-q8_0 | 7 | 34 | 100 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | base | 7 | 64 | 178 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | base-q5_0 | 7 | 37 | 197 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | base-q8_0 | 7 | 45 | 182 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | small | 7 | 167 | 571 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | small-q5_0 | 7 | 72 | 602 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | small-q8_0 | 7 | 103 | 585 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | medium | 7 | 471 | 1724 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | medium-q5_0 | 7 | 180 | 1782 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | medium-q8_0 | 7 | 275 | 1708 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | large | 7 | 944 | 3029 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | large-q5_0 | 7 | 347 | 3121 | 7765770 |
| M1 Pro | MacOS 13.3.1 |  NEON BLAS | large-q8_0 | 7 | 544 | 3036 | 7765770 |


The quantized models do not improve the Encoder speed in general on M1, but they do for WASM SIMD.
They also improve the Decoder speed, but unfortunately we don't have benchmarks for that yet.

The memory increase is due to disabling the Flash Attention kernel since it does not provide much benefit anymore and when using cuBLAS it actually becomes a drawback.

You can try to re-enable the Flash Attention and see how this affects the performance on your system. Just uncomment the following line:

https://github.com/ggerganov/whisper.cpp/blob/7765770f89e5a34d80a0fc4ace7707ab3275bc2f/whisper.cpp#L104

**Comment by byte-6174** [comment]
I have noticed that 8bit quantization produces a model alright, however when given the same wav file to transcribe as to 4/5bit, the 8bit model produces garbage!
(Running on aarch64)
anyone else experiencing this?!
