### ISSUE TITLE
iOS performance issue

### ISSUE THREAD

**Issue by yujinqiu** [ggerganov/whisper.cpp#92]
Hi, 
From the demo you show it takes **1.248s** on iphone 13 mini.  But it takes **24.393s** on my  iPhone 12 iOS 16.1. 

my build commit hash:
```
commit 4c68f4cac00ee693106d8501d4f5fb670fe0294e (HEAD -> master, origin/master, origin/HEAD)
Author: Georgi Gerganov <ggerganov@gmail.com>
Date:   Mon Oct 24 18:28:23 2022 +0300

    main : fix SRT timestamp to use comma "," instead of dot "."
```

![image](https://user-images.githubusercontent.com/785405/197906614-a6c61140-6dd6-45c0-976e-b10f12d24697.png)

**Comment by ggerganov** [comment]
Double-check that you are building it in Release:

<img width="947" alt="image" src="https://user-images.githubusercontent.com/1991296/197382607-9e1e6d1b-79fa-496f-9d16-b71dc1535701.png">

**Comment by ggerganov** [comment]
Just curious - did it improve the performance, and if it did - how long does it take on iPhone 12?

**Comment by yujinqiu** [comment]
@ggerganov  Change `Build Configuration` to `Release` works on my  iPhone12. 
It takes from 24.393s down to  1.434s. 
What's the difference between Release and Debug of `Build Configuration` ?

**Comment by ggerganov** [comment]
When building in `Release` the compiler applies a lot of optimizations to make the app run faster. However, due to these optimizations, you lose some debug information (e.g. debug symbols, code/variables that are optimized-out, etc). Therefore, you typically use `Debug` while you are developing your software and when you know it works correctly, you build it in `Release` and ship it. This is what most people who use a debugger do. Personally, I always build in `Release` and just use print statements to debug my programs.

**Comment by yujinqiu** [comment]
Your reply make everything clear, thanks. I'll close this issue.
