### ISSUE TITLE
Which constraint is the CoreML given for usage on the M1?

### ISSUE THREAD

**Issue by janngobble** [ggerganov/whisper.cpp#966]
I know you can only specify CPU, CPU/GPU, or CPU/GPU/ANE constraints for Core ML code.

The question is, which one is whisper.cpp using?

The reason I ask is that it flies when it is running as the only process on the M1, but when I run ffmpeg and indicate ffmpeg should use the hevc_videotoolbox (which mainly leans on the GPU) whisper slows to a crawl. I know programming and realize that ffmpeg can take a LOT of power to run AND can lock out other tasks, but if I lock ffmpeg to GPU I wanted to know what the constraint was in whisper so I can decide how to proceed on running other tasks on the same M1.

Thanks.

**Comment by colinc** [comment]
Without setting a MLModelConfiguration the predictions are run on the ANE. However, after each prediction, the process is still CPU bound, mostly by ggml_graph_compute_thread (over 80% of the CPU time) with roughly a quarter of that time spent in ggml_compute_forward_mul_mat.

Using MLComputeUnitsCPUAndGPU, there is a significant speed up on certain hardware (i.e. Max/Ultra chipsets) because the GPU is astronomically faster at returning predictions vs the ANE (like 35~37ms on the M1 Ultra GPU vs ~1070ms on the ANE). However, the same above constraints still currently apply with nearly all of the time now inside of ggml_graph_compute_thread.

**Comment by colinc** [comment]
Here's a visual illustration of with and without the MLModelConfiguration (using MLComputeUnitsCPUAndGPU) on an M1 Ultra:

<img width="786" alt="Screenshot 2023-06-12 at 4 36 59 PM" src="https://github.com/ggerganov/whisper.cpp/assets/16424/ecde6a9f-ebda-40a9-a230-baac2bedb67b">
<img width="780" alt="Screenshot 2023-06-12 at 4 40 44 PM" src="https://github.com/ggerganov/whisper.cpp/assets/16424/22fbfb02-3f22-4443-aec2-33262812e2a6">

**Comment by janngobble** [comment]
Thanks so much. This explains a LOT!

**Comment by janngobble** [comment]
Thanks so much. This explains a LOT!

**Comment by ggerganov** [comment]
The CPU part (i.e. the Decoder) can be offloaded to the GPU by integrating the Metal support similar to what we did in `llama.cpp`. When we do that, `whisper.cpp` will become really fast on Apple Silicon

Will open a separate issue about this topic soon

**Comment by janngobble** [comment]
> The CPU part (i.e. the Decoder) can be offloaded to the GPU by integrating the Metal support similar to what we did in `llama.cpp`. When we do that, `whisper.cpp` will become really fast on Apple Silicon
> 
> Will open a separate issue about this topic soon

Please do! Thanks!!!
